# -*- coding: utf-8 -*-
"""streamlit-app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKi69H5tDdISLjUd8y_hSTEGE_YQ3XKM
"""

!pip install streamlit
!streamlit run app.py

import streamlit as st
import pandas as pd
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns

# ===========================
# 1. APP CONFIG
# ===========================
st.set_page_config(page_title="Hybrid Diabetes Predictor",
                   layout="wide",
                   page_icon="🩺")

st.markdown("""
    <style>
        .main {
            background: linear-gradient(135deg, #d9e4f5 0%, #f5f7fa 100%);
            padding: 20px;
        }
        .stButton>button {
            background-color: #0066cc;
            color: white;
            border-radius: 12px;
            padding: 10px 20px;
            font-size: 18px;
        }
        .stProgress > div > div > div {
            background-color: #ff4b4b;
        }
    </style>
""", unsafe_allow_html=True)

st.title("🔮 **Hybrid Diabetes Prediction System (ML + Fuzzy)**")
st.write("Sistem prediksi diabetes berbasis Random Forest dan Fuzzy Logic Control System.")

# ===========================
# 2. LOAD & TRAIN MODEL
# ===========================
df = pd.read_csv("diabetes.csv")

cols_with_zero = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]
for col in cols_with_zero:
    df[col] = df[col].replace(0, df[col].median())

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

model = RandomForestClassifier()
model.fit(X, y)

# ===========================
# 3. FUZZY SYSTEM
# ===========================
glucose = ctrl.Antecedent(np.arange(0, 201, 1), 'glucose')
bmi = ctrl.Antecedent(np.arange(0, 71, 1), 'bmi')
age = ctrl.Antecedent(np.arange(10, 101, 1), 'age')
risk = ctrl.Consequent(np.arange(0, 101, 1), 'risk')

glucose['low'] = fuzz.trimf(glucose.universe, [0, 0, 110])
glucose['medium'] = fuzz.trimf(glucose.universe, [90, 130, 170])
glucose['high'] = fuzz.trimf(glucose.universe, [150, 200, 200])

bmi['normal'] = fuzz.trimf(bmi.universe, [0, 0, 25])
bmi['overweight'] = fuzz.trimf(bmi.universe, [20, 30, 40])
bmi['obese'] = fuzz.trimf(bmi.universe, [35, 70, 70])

age['young'] = fuzz.trimf(age.universe, [10, 10, 35])
age['adult'] = fuzz.trimf(age.universe, [30, 50, 60])
age['elder'] = fuzz.trimf(age.universe, [55, 100, 100])

risk['low'] = fuzz.trimf(risk.universe, [0, 0, 40])
risk['medium'] = fuzz.trimf(risk.universe, [30, 50, 70])
risk['high'] = fuzz.trimf(risk.universe, [60, 100, 100])

rule1 = ctrl.Rule(glucose['high'] & bmi['obese'], risk['high'])
rule2 = ctrl.Rule(glucose['medium'] & bmi['overweight'], risk['medium'])
rule3 = ctrl.Rule(glucose['low'] & bmi['normal'], risk['low'])
rule4 = ctrl.Rule(age['elder'] & glucose['high'], risk['high'])
rule5 = ctrl.Rule(bmi['obese'] & age['adult'], risk['high'])

system = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5])
sim = ctrl.ControlSystemSimulation(system)

def fuzzy_predict(g, b, a):
    sim.input['glucose'] = g
    sim.input['bmi'] = b
    sim.input['age'] = a
    sim.compute()
    return sim.output['risk']

def hybrid_predict(row):
    ml_score = model.predict_proba([row])[0][1] * 100
    fuzzy_score = fuzzy_predict(row[1], row[4], row[7])
    return (0.7 * ml_score) + (0.3 * fuzzy_score)

# ===========================
# 4. UI INPUT PREMIUM
# ===========================
st.header("📝 Input Data Pasien")

col1, col2, col3 = st.columns(3)

with col1:
    Preg = st.number_input("Pregnancies", 0, 20, 1)
    Glc = st.number_input("Glucose", 0, 200, 120)

with col2:
    BP = st.number_input("Blood Pressure", 0, 150, 70)
    ST = st.number_input("Skin Thickness", 0, 100, 20)

with col3:
    BMI = st.number_input("BMI", 0.0, 70.0, 25.0)
    DPF = st.number_input("Diabetes Pedigree Function", 0.0, 3.0, 0.5)
    Age = st.number_input("Age", 10, 100, 30)

# ===========================
# 5. PREDIKSI
# ===========================
if st.button("🔮 Prediksi Sekarang"):

    data = [Preg, Glc, BP, ST, BMI, DPF, Age]
    hasil = hybrid_predict(data)

    st.subheader("🎯 Skor Risiko Diabetes")
    st.progress(int(hasil))

    st.write(f"### Risiko Anda: **{hasil:.2f}%**")

    if hasil > 50:
        st.error("⚠ Tinggi! Risiko Diabetes signifikan.")
    else:
        st.success("✔ Rendah! Risiko Diabetes terkendali.")

# ===========================
# 6. ANALISIS MODEL (CONFUSION MATRIX + ROC)
# ===========================
st.header("📊 Evaluasi Model Machine Learning")

y_pred = model.predict(X)

st.subheader("Confusion Matrix")
cm = confusion_matrix(y, y_pred)
fig = plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
st.pyplot(fig)

st.subheader("Classification Report")
st.text(classification_report(y, y_pred))

st.subheader("ROC Curve")
fpr, tpr, th = roc_curve(y, model.predict_proba(X)[:,1])
roc_auc = auc(fpr, tpr)

fig2 = plt.figure(figsize=(5,4))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
st.pyplot(fig2)